# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

jobs:
- job: 'BuildMac'
  displayName: 'Mac'
  variables:
    - group: 'Keys'

  pool:
    vmImage: 'macOS-10.14'
    demands: msbuild

  steps:
  - checkout: self
    submodules: 'true'

  - template: common-dotnet.yml@templates
  - template: common-macos.yml@templates

  - task: NuGetCommand@2
    displayName: 'NuGet restore'

  - task: PowerShell@2
    displayName: 'PreBuild Script'
    inputs:
      targetType: filePath
      filePath: ./devops/PreBuild.ps1
      arguments: 'Codefoco.CYRTextView CYRTextView.nuspec'

  - task: MSBuild@1
    displayName: 'Build solution CYRTextView.sln'
    inputs:
      solution: CYRTextView.sln
      configuration: Release

  - script: 'nuget setapikey $(apikey)'
    displayName: 'Set NuGet API Key'

  - task: PowerShell@2
    displayName: 'Package NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Package.ps1
      arguments: 'Codefoco.CYRTextView CYRTextView.nuspec'

  - script: 'mv *.nupkg Codefoco.CYRTextview.nupkg'
    displayName: 'Rename NuGet package'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Codefoco.CYRTextview.nupkg Artifact'
    inputs:
      PathtoPublish: Codefoco.CYRTextview.nupkg
      ArtifactName: Codefoco.CYRTextview.nupkg

  - task: PowerShell@2
    displayName: 'Publish NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Publish.ps1
      arguments: Codefoco.CYRTextView

  - template: send-telegram.yml@templates
